Curso_Trabajo/urls.py
from django.contrib import admin
from django.urls import path, include
from inventario.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventario/', include('inventario.urls')), # Incluye las URLs de la app inventario de urls.py
    path('', index_view, name='index'), # Vista principal
    path('ventas/', include('ventas.urls')), # Incluye las URLs de la app ventas de urls.py
]

inventario/urls.py
from django.urls import path
from . import views

app_name = 'inventario'

urlpatterns = [
    path('productos/', views.productos_disponibles, name='productos_disponibles'),
    path('crear/', views.crear_producto, name='crear_producto'),
    path('editar/<int:pk>/', views.editar_producto, name='editar_producto'), #<int:pk es para capturar el ID del producto a editar
    path('eliminar/<int:pk>/', views.eliminar_producto, name='eliminar_producto'), # Ruta para eliminar un producto
]

ventas/urls.py
from django.urls import path
from . import views

app_name = 'ventas'

urlpatterns = [
    path('clientes/', views.lista_clientes, name='listado_cliente'),
    path('clientes/nuevo/', views.crear_cliente, name='formulario_cliente'),
    path('clientes/crear_venta/<int:cliente_id>/', views.crear_venta, name='crear_venta'),
    path('', views.listado_ventas, name='listado_ventas'),
    path('clientes/eliminar/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'),
]

inventario/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class MovimientoStock(models.Model):
    producto_id = models.ForeignKey(Producto, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    cantidad = models.IntegerField()
    tipo_movimiento = models.CharField(max_length=50)  # e.g., 'entrada', 'salida'
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.tipo_movimiento} - {self.producto_id.nombre} - {self.cantidad}"
    

ventas/models.py
from django.db import models
from inventario.models import Producto

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    

    def __str__(self):
        return self.nombre

class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"Venta de {self.producto} a {self.cliente.nombre}"
    
class ItemVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey('inventario.Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f"{self.cantidad} x {self.producto} @ {self.precio_unitario}"

    def total(self):
        return self.cantidad * self.precio_unitario

inventario/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'stock', 'categoria']

ventas/forms.py
from django import forms
from .models import Cliente, ItemVenta

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre']

class ItemVentaForm(forms.ModelForm):
    class Meta:
        model = ItemVenta
        fields = ['producto', 'cantidad', 'precio_unitario']

inventario/views.py
from django.shortcuts import render, get_object_or_404
from .models import Producto
from .forms import ProductoForm
from django.shortcuts import redirect
# Create your views here.
def productos_disponibles(request):
    productos = Producto.objects.filter(stock__gt=0)
    return render(request, 'inventario/productos.html', {'productos': productos})

def crear_producto(request):
    form = ProductoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('inventario:productos_disponibles')
    return render(request, 'inventario/formulario_producto.html', {'form': form})

def editar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    form = ProductoForm(request.POST or None, instance=producto)
    if form.is_valid():
        form.save()
        return redirect('inventario:productos_disponibles')
    return render(request, 'inventario/formulario_producto.html', {'form': form, 'producto': producto})

def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        producto.delete()
        return redirect('inventario:productos_disponibles')
    return render(request, 'inventario/confirmar_eliminar.html', {'producto': producto})

def index_view(request):
    return render(request, 'base.html')

ventas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente, Venta, ItemVenta
from .forms import ClienteForm, ItemVentaForm
from django.utils import timezone

# Create your views here.

def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ventas:listado_cliente')
    else:
        form = ClienteForm()
    return render(request, 'ventas/formulario_cliente.html', {'form': form})

def lista_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'ventas/listado_cliente.html', {'clientes': clientes})

def crear_venta(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        form = ItemVentaForm(request.POST)
        if form.is_valid():
            venta = Venta.objects.create(cliente=cliente, fecha = timezone.now())
            item = form.save(commit=False)
            item.venta = venta
            item.save()
            return redirect('ventas:listado_ventas')
    else:
        form = ItemVentaForm()
    return render(request, 'ventas/crear_venta.html', {'form': form, 'cliente': cliente})

def listado_ventas(request):
    ventas = Venta.objects.all()
    return render(request, 'ventas/listado_ventas.html', {'ventas': ventas})

def eliminar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        cliente.delete()
        return redirect('ventas:listado_cliente')
    return render(request, 'ventas/confirmar_eliminar_cliente.html', {'cliente': cliente})

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sistema de Gestión{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-4">
        <h1 class="mb-4">Sistema de Ventas e Inventario</h1>
        <div class="mb-4">
            <a href="{% url 'inventario:productos_disponibles' %}" class="btn btn-outline-primary">Stock de Productos</a>
            <a href="{% url 'inventario:crear_producto' %}" class="btn btn-outline-success">Crear Producto</a><br>
            <a href="{% url 'ventas:listado_cliente' %}" class="btn btn-outline-primary">Clientes</a>
            <a href="{% url 'ventas:formulario_cliente' %}" class="btn btn-outline-success">Crear Cliente</a><br>
            <a href="{% url 'ventas:listado_ventas' %}" class="btn btn-outline-info">Ventas</a>
        </div>
        {% block content %}<h2>ESTA ES LA BASE DEL PROYECTO</h2>{% endblock %}
    </div>
</body>
</html>

templates/inventario/confirmar_eliminar.html
{% extends "base.html" %}

{% block title %}
Confirmar Eliminación de Producto
{% endblock title %}

{% block content %}
<h2>¿Estás seguro de que deseas eliminar el producto "{{ producto.nombre }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>
{% endblock content %}

templates/inventario/formulario_producto.html
{% extends "base.html" %}


{% block title %}
Formulario de Producto
{% endblock title %}

{% block content %}

{% if form.instance.pk %}
<h2>Editar</h2>
{% else %}
<h2>Crear</h2>
{% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock content %}

templates/inventario/productos.html
{% extends "base.html" %}

{% block title %}
Productos Disponibles
{% endblock title %}

{% block content %}

<h2>Productos disponibles</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Stock</th>
      <th>Categoría</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
    <tr>
      <td>{{ producto.nombre }}</td>
      <td>${{ producto.precio }}</td>
      <td>{{ producto.stock }}</td>
      <td>{{ producto.categoria.nombre }}</td>
      <td>
        <a href="{% url 'inventario:editar_producto' producto.pk %}" class="btn btn-warning btn-sm">Editar</a>
        <a href="{% url 'inventario:eliminar_producto' producto.pk %}" class="btn btn-danger btn-sm">Eliminar</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

templates/ventas/confirmar_eliminar_cliente.html
{% extends 'base.html' %}

{% block content %}

<h2>¿Estás seguro de que deseas eliminar al cliente "{{ cliente.nombre }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar Cliente</button>
    <a href="{% url 'ventas:listado_cliente' %}" class="btn btn
-secondary">Cancelar</a>
</form>
{% endblock content %}

templates/ventas/crear_venta.html
{% extends 'base.html' %}


{% block title %}Crear Venta{% endblock title %}

{% block content %}

<h2>Crear Venta para {{ cliente.nombre }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar Venta</button>
</form>
{% endblock content %}

templates/ventas/formulario_cliente.html
{% extends 'base.html' %}

{% block title %}Crear Cliente{% endblock title %}

{% block content %}

<h2>Crear Cliente</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar Cliente</button>
</form>

{% endblock content %}

templates/ventas/listado_cliente.html
{% extends "base.html" %}

{% block title %}
Productos Disponibles
{% endblock title %}

{% block content %}

<h2>Listado Clientes</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for cliente in clientes %}
    <tr>
      <td>{{ cliente.nombre }}</td>
      <td>
      <a href="{% url 'ventas:crear_venta' cliente.pk %}" class="btn btn-primary btn-sm">Crear Venta</a>
      <a href="{% url 'ventas:eliminar_cliente' cliente.pk %}" class = "btn btn-danger btn-sm">Eliminar Cliente</a>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

templates/ventas/listado_ventas.html
{% extends 'base.html' %}

{% block title %}
Lista de Ventas
{% endblock title %}

{% block content %}

<h2>Lista de Ventas</h2>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Cliente</th>
    <th>Fecha</th>
    </tr>
  </thead>
  <tbody>
    {% for venta in ventas %}
    <tr>
    <td>{{ venta.cliente }}</td>
    <td>{{ venta.fecha }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}